version: '2.0'
services:
  sonarqube:
    build:
      context: sonarqube/
      labels:
        server: myserver
    ports:
      - 9001:9001
      - 9093:9093
    container_name: buildimages_sonarqube
  jenkins:
    build:
      context: jenkins/
      labels:
        server: myserver
    privileged: true
    user: root
    ports:
      - 8081:8081
      - 50001:50001
    container_name: buildimages_jenkins
    volumes:
      - /tmp/jenkins:/var/jenkins_home #Remember that, the tmp directory is designed to be wiped on system reboot.
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - sonarqube
#
