
version: '2.0'
services:
  jenkins:
    build:
      context: jenkins/
    privileged: true
    user: root
    ports:
      - 8081:8081
      - 50001:50001
    container_name: buildimages_jenkins
    volumes:
      - /tmp/jenkins:/var/jenkins_home #Remember that, the tmp directory is designed to be wiped on system reboot.
      - /var/run/docker.sock:/var/run/docker.sock
